### PR TITLE
Add and edit docs

### PR DESCRIPTION
**Pull request by zanemit**
Added / edited several docs in `Core` and `Fundamentals`. 

`DigitalOutput` in daqmx and `KeyDown` in windows_input contain images of basic workflow examples under "Tips". Not sure if that's where we want such examples to go?

### CODE REVIEW

**Review by Peter-Vincent — APPROVED** [review]
In the digital_output.md it may be helpful to clarify that one needs to respect the nyquist sampling theorem.

In camera_capture.md, is it really only from webcams?  I thought one could specify the camera to be used?

In key_down.md, in most cercumstances using the KeyDown from the shaders library is preferable,  but thats really a side point.

**Comment by zanemit** [comment]
All good points, thank you @PeterVincent96 !

1. I agree it was not clear enough and have attempted to clarify the part about frequency in `digital_output.md`. Let me know if you think it should be made more obvious rather than left as part of a "tip". 
I have also added a comment about the Nyquist sampling theorem to `SampleRate` of `analog_output.md` and `analog_input.md`. 

2. You are correct, I believe any camera compatible with DirectShow can be used. I have amended the brief to reflect this.

3. I have not needed to use the Shaders library and do not feel competent to expand on this point, so I have added your comment to `key_down.md` word for word. Please feel free to add to this, as I will surely not be the only one curious about the rationale behind that tip (e.g. are there functional differences in the `KeyDown` nodes themselves, or is the Shaders `KeyDown` preferable only in the context of a workflow due to compatibility issues between WindowsInput and Shaders).

**Comment by spewil** [comment]
Looks great, I'd like to start working on the shaders module... it's a good one. Maybe we can make a project for this.

**Review by spewil — COMMENTED** [review]
Looks great-- just add more links to things you reference. Eventually we can have lots of internal links as well (e.g. to the relevant Shaders module doc)

**Pull request merged**
